apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 158039853344-e6dbrbj6l5865ji3fl35pcb4r9fpkufp.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://34.224.7.141.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
